import { Inter } from "next/font/google";
import style from './page.module.scss'
import "../styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={style.Layout}>{children}</body>
    </html>
  );
}
